#!/usr/bin/env bash
set -euo pipefail

development_dir="${DEVELOPMENT_DIR:-${HOME}/development}"
copilot_config_dir="${HOME}/.copilot"
copilot_instructions_source="/usr/local/share/copilot-workspace/copilot-instructions.md"
copilot_instructions_target="${copilot_config_dir}/copilot-instructions.md"
bashexports_path="${HOME}/.bashexports"

mkdir -p "${HOME}/.config/gh" "${copilot_config_dir}" "${development_dir}"

if [[ -f "${copilot_instructions_source}" ]]; then
    install -m 0644 "${copilot_instructions_source}" "${copilot_instructions_target}"
fi

notification_env_vars=(
    COPILOT_NTFY_TOPIC
    COPILOT_NTFY_SERVER
    COPILOT_NTFY_PRIORITY
    COPILOT_NTFY_DEBUG_LOG
    COPILOT_NTFY_TITLE
)

{
    printf '# Generated by docker-entrypoint.sh\n'
    for var_name in "${notification_env_vars[@]}"; do
        if [[ -v "${var_name}" ]] && [[ -n "${!var_name}" ]]; then
            printf 'export %s=%q\n' "${var_name}" "${!var_name}"
        fi
    done
} > "${bashexports_path}"

if ! gh auth status >/dev/null 2>&1 && [[ -n "${COPILOT_HOST_GH_TOKEN:-}" ]]; then
    rm -f "${HOME}/.config/gh/hosts.yml"
    printf '%s' "${COPILOT_HOST_GH_TOKEN}" | gh auth login \
        --hostname github.com \
        --with-token \
        --git-protocol "${COPILOT_HOST_GH_GIT_PROTOCOL:-https}" \
        >/dev/null
fi

exec "$@"
